# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import interaction_pb2 as interaction__pb2


class InteractStub(object):
    """The interact service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RobotConnect = channel.unary_unary(
                '/interaction.Interact/RobotConnect',
                request_serializer=interaction__pb2.RobotConnectRequest.SerializeToString,
                response_deserializer=interaction__pb2.RobotConnectReply.FromString,
                )
        self.RobotSend = channel.unary_unary(
                '/interaction.Interact/RobotSend',
                request_serializer=interaction__pb2.RobotInput.SerializeToString,
                response_deserializer=interaction__pb2.RobotOutput.FromString,
                )


class InteractServicer(object):
    """The interact service definition.
    """

    def RobotConnect(self, request, context):
        """Sends connection confirm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RobotSend(self, request, context):
        """Sends information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InteractServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RobotConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.RobotConnect,
                    request_deserializer=interaction__pb2.RobotConnectRequest.FromString,
                    response_serializer=interaction__pb2.RobotConnectReply.SerializeToString,
            ),
            'RobotSend': grpc.unary_unary_rpc_method_handler(
                    servicer.RobotSend,
                    request_deserializer=interaction__pb2.RobotInput.FromString,
                    response_serializer=interaction__pb2.RobotOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interaction.Interact', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Interact(object):
    """The interact service definition.
    """

    @staticmethod
    def RobotConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/interaction.Interact/RobotConnect',
            interaction__pb2.RobotConnectRequest.SerializeToString,
            interaction__pb2.RobotConnectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RobotSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/interaction.Interact/RobotSend',
            interaction__pb2.RobotInput.SerializeToString,
            interaction__pb2.RobotOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
